### ISSUE TITLE
Error when make the renderer

### ISSUE THREAD

**Issue by XuelianCheng** [autonomousvision/connecting_the_dots#3]
Hi, 

Thanks for sharing your code! I try to make within the renderer directory as you guided. It needs to cd a folder named pyrender. But I did not find it in the renderer directory. Is that possible for you to check that?

Here is the error information:
make: Circular render/render_gpu.cu <- render/render_gpu.cu.o dependency dropped.
make: Circular render/stdlib_cuda.cu <- render/stdlib_cuda.cu.o dependency dropped.
cd pyrender; \
python setup.py build_ext --inplace
/bin/sh: 1: cd: can't cd to pyrender
using cuda
running build_ext

**Comment by yiyiliao** [comment]
Thanks for reporting the error. It should be fixed now.

**Comment by XuelianCheng** [comment]
Hi Yiyi,

Many thanks for the reply!

After updating the Makefile as you suggested, there is the still error when
I run  ./create_syn_data.sh.  Any suggestions for this? Cause I am not
familiar with C++.  Is that a compile problem?

.................
load
/home/chengxuelian/ShapeNetCoreV2/03001627/13990109140043c919fb4103277a6b93/models/model_normalized.obj
load
/home/chengxuelian/ShapeNetCoreV2/03001627/13b6648bdc843b767b5f4d129cc2873d/models/model_normalized.obj
loaded 100 objects
write settings to
/home/chengxuelian/synthetic/data/syn/settings.pkl
>
/home/chengxuelian/connecting_the_dots-master/data/create_syn_data.py(98)create_data()
-> verts, faces, colors, normals = get_mesh(rng)
(Pdb) c
Traceback (most recent call last):
  File "create_syn_data.py", line 260, in <module>
    create_data(*args)
  File "create_syn_data.py", line 98, in create_data
    verts, faces, colors, normals = get_mesh(rng)
AttributeError: module 'renderer' has no attribute 'PyRenderInput'

Thanking you!
Xuelian

**Comment by yiyiliao** [comment]
Hi Xuelian,

Could you try to pull the latest version and run "make clean" before "make" in the renderer folder? 
Let me know if it does not work.

Yiyi

**Comment by AvrilCheng** [comment]
Hi Yiyi,

Thank you so much for your instant reply.

Yes, I have tried the latest version but it still didn't work.  The same
error was reported.

==================================
Xuelian Cheng
E-mail: chengxuelian28@gmail.com


Yiyi Liao <notifications@github.com> 于2019年7月29日周一 下午6:05写道：

**Comment by AvrilCheng** [comment]
[image: image.png]

Here is the error information. Thanks.

==================================
Xuelian Cheng
E-mail: chengxuelian28@gmail.com


程雪莲 <chengxuelian28@gmail.com> 于2019年7月29日周一 下午6:52写道：

**Comment by AvrilCheng** [comment]
Here is the error information. Thanks!

**Comment by XuelianCheng** [comment]
Hi Yiyi,

Thank you so much for your instant reply. 

I just found the error is caused by the low version of cuda. LOL

**Comment by Gthq** [comment]
Hi Yiyi,
  What should I do when I run  ./create_syn_data.sh, 
running build_ext
Traceback (most recent call last):
  File "create_syn_data.py", line 14, in <module>
    import renderer
  File "../renderer/__init__.py", line 4, in <module>
    from .cyrender import *
ImportError: ../renderer/cyrender.cpython-35m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
 occured,
my cuda infomation is:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
